/* The responsive hero set, shared by the page that renders the photograph and
   the layout that preloads it, so the two can never drift apart.
   Generated by scripts/hero_images.mjs; the 1920 entry is the untouched
   original, which is also the og:image. */
export const heroSrcset = [
  '/assets/hero/field-640.webp 640w',
  '/assets/hero/field-960.webp 960w',
  '/assets/hero/field-1280.webp 1280w',
  '/assets/hero/field-1600.webp 1600w',
  '/assets/field.webp 1920w',
].join(', ');
